kind: pipeline
name: licslan


steps:
- name: Maven编译打包
  image: maven:3-jdk-8
  volumes:
  - name: cache
    path: /root/.m2
  commands:
    - mvn package docker:build
  volumes:
  - name: docker
    path: /var/run/docker.sock


- name: 运行镜像
  image: licslan
  commands: 
    - docker run -it -d --name springboot -p 7777:7777 licslan/springboot 
  when:
    event:
    - push


volumes:
- name: docker
  host:
    path: /var/run/docker.sock
