kind: pipeline
name: licslan

steps:
- name: Maven编译打包
  image: maven:3-jdk-8
  commands:
    - echo "hello docker"
    - mvn clean install

- name: 制作镜像
  image: docker:dind
  commands:
    - docker build -t springio/gs-spring-boot-docker:v1 . 

- name: 运行镜像
  image: springio/gs-spring-boot-docker
  commands:
     - docker run -it -d --name springboot -p 7777:8080 springio/gs-spring-boot-docker
  when:
    event:
    - push

