kind: pipeline
name: licslan


steps:
- name: Maven编译打包
  image: maven:3-jdk-8
  volumes:
  - name: cache
    path: /root/.m2
  commands:
    - echo "hello docker"

- name: 制作镜像
  image: maven
  commands:
    - mvn clean package -Dmaven.test.skip=true docker:build 

- name: 运行镜像
  image: runimages
  commands:
     - docker run -it -d --name springboot -p 7777:8080 springio/drone
  when:
    event:
    - push

