kind: pipeline
name: LICSLAN

steps:
- name: restore-cache  
  image: maven:3-jdk-8
  commands: 
    - mvn clean install -Dmaven.test.skip=true


#- name: build images  
#  image: plugins/docker
#  commands:
#  - sleep 5 # give docker enough time to start
#  - docker -v
#  - nohup dockerd &
#  - sleep 10
#  - docker build -t springio/licslan:latest .
#  - sleep 10 
#  - docker run -p 7777:8080 -d springio/licslan:latest  

- name: build images
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run
  commands:
  - sleep 5 # give docker enough time to start
  - docker ps -a
  - docker build -t springio/licslan:latest .
#  - sleep 10
#  - docker run -p 80:8080 -d springio/licslan:latest

- name: run images
  image: plugins/docker
  commands: 
  - nohup dockerd
  - docker run -p 80:8080 -d springio/licslan:latest



services:
- name: docker
  image: docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run

volumes:
- name: dockersock
  temp: {}



trigger:
  branch:
  - master
  event:
  - push
