kind: pipeline
name: licslan


steps:
- name: Maven编译
  image: maven:3-jdk-8
  volumes:
  - name: cache
    path: /root/.m2
  commands:
    - mvn clean install

- name: 制作镜像
  image: boot:hello
  commands:
    - mvn package docker:build

- name: 运行镜像
  image: licslan
  commands: 
    - docker run -it -d --name springboot -p 7777:7777 licslan/springboot 
  when:
    event:
    - push
