kind: pipeline
name: LICSLAN

steps:
- name: restore-cache  
  image: maven:3-jdk-8
  commands: 
    - mvn clean install -Dmaven.test.skip=true


- name: build images  
  image: plugins/docker
  commands:
  - sleep 5 # give docker enough time to start
  - docker -v
  - nohup dockerd &
  - docker build -t springio/licslan:latest .
  - sleep 10 
  - docker run -p 7777:8080 -d springio/licslan:latest  

trigger:
  branch:
  - master
  event:
  - push
