kind: pipeline
name: licslan

steps:
- name: build
  image: java:openjdk-8
  commands:
  - sh deploy.sh

- name: integration
  image: java:openjdk-8
  commands:
  - java -veriosn
  when:
    event:
    - push
