kind: pipeline
name: licslan


steps:
- name: Maven编译打包
  image: maven:3-jdk-8
  volumes:
  - name: cache
    path: /root/.m2
  commands:
    - echo "hello docker"
    - mvn clean install -Dmaven.test.skip=true

- name: 制作镜像
  image: maven
  commands:
    - docker build -t springio/gs-spring-boot-docker .

- name: 运行镜像
  image: springio/gs-spring-boot-docker
  commands:
     - docker run -it -d --name springboot -p 7777:8080 springio/gs-spring-boot-docker
  when:
    event:
    - push

