kind: pipeline
name: LICSLAN

steps:
- name: restore-cache  
  image: maven:3-jdk-8
  commands: 
    - mvn clean install -Dmaven.test.skip=true

- name: run images
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - docker ps -a
  #- docker stop `docker ps -a| grep x | awk '{print $1}' `
  #- docker rm   `docker ps -a| grep x | awk '{print $1}' `
  - docker build -t springio/licslan:latest .
  - sleep 10
  - docker run --name x -p 80:8080 -d springio/licslan:latest

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock



trigger:
  branch:
  - master
  event:
  - push
