kind: pipeline
name: licslan

steps:
- name: build
  image: docker.io/maven:latest
  commands:
  - mvn clean package -Dmaven.test.skip=true

- name: deploy
  image: java:openjdk-8
  commands:
  - nohup java -jar target/drone-0.0.1-SNAPSHOT.jar &
  when:
    event:
    - push
